import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

// Bảng màu lấy từ html/index.html (Material 3 tokens)
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#004395',
        'on-error': '#ffffff',
        'surface-container-low': '#f2f3ff',
        primary: '#004ac6',
        'on-surface': '#131b2e',
        'surface-dim': '#d2d9f4',
        'tertiary-container': '#0f69dc',
        'tertiary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container-high': '#e2e7ff',
        secondary: '#3755c3',
        'primary-container': '#2563eb',
        'inverse-surface': '#283044',
        'secondary-fixed-dim': '#b8c4ff',
        'outline-variant': '#c3c6d7',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00217a',
        'surface-container': '#eaedff',
        'surface-bright': '#faf8ff',
        'secondary-fixed': '#dde1ff',
        'surface-container-highest': '#dae2fd',
        'on-tertiary-container': '#edf0ff',
        'surface-tint': '#0053db',
        'surface-container-lowest': '#ffffff',
        outline: '#737686',
        background: '#faf8ff',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-primary': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary': '#ffffff',
        'on-background': '#131b2e',
        error: '#ba1a1a',
        'on-secondary-fixed': '#001453',
        'on-surface-variant': '#434655',
        'tertiary-fixed-dim': '#adc6ff',
        'secondary-container': '#708cfd',
        'on-primary-container': '#eeefff',
        'surface-variant': '#dae2fd',
        tertiary: '#0051b1',
        surface: '#faf8ff',
        'primary-fixed': '#dbe1ff',
        'inverse-on-surface': '#eef0ff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#173bab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
};
